baseURL = ""
languageCode = "en-us"
title = "Los Alamos Al"
theme = "beautifulhugo"
buildDrafts = true
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  subtitle = "Semi-retired computer scientist. Prepping for the killer app."
  logo = "img/al-poster-edges-color.png"
  dateFormat = "January 2, 2006"
  readingTime = false

[Author]
  name = "Allen McPherson"
  website = "losalamosal.me"
  email = "al@losalamosal.me"
  github = "losalamosal"
  twitter = "losalamosal"
  linkedin = "allenmcpherson"
  stackoverflow = "users/227441/los-alamos-al"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
